spring:
  datasource:
    url: jdbc:mysql://localhost:3307/user
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        connection:
          isolation: 8
server:
  port: 4446